name: Every fourtysix Minutes

on:
  schedule:
    - cron: '*/46 * * * *'
  workflow_dispatch:

jobs:
  call-api-job:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase GET Function 'qtsquery'
        run: |
          curl -f -L -X GET 'https://ciyoandzjezgqxjpcrin.supabase.co/functions/v1/clarifai' \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
